"""sua_nullable_role_tier

Revision ID: 79caea7ab4a3
Revises: 
Create Date: 2026-01-09 03:09:38.594413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79caea7ab4a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='userrole'),
               nullable=False)
    op.alter_column('users', 'tier',
               existing_type=postgresql.ENUM('FREE', 'VIP', name='usertier'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tier',
               existing_type=postgresql.ENUM('FREE', 'VIP', name='usertier'),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
